# Contao configuration
contao:
    url_suffix: ""
    image:
        imagine_service: contao.image.imagine.gd

bwein_backend_customizer:
    header_title: 'yatelier'
    header_color: '#0D061D'

doctrine:
    dbal:
        connections:
            default:
                options:
                    1002: "SET SESSION sql_mode=(SELECT CONCAT(@@sql_mode, ',TRADITIONAL'))"
